### ISSUE TITLE
Two clicks to get to Admin Menu

### ISSUE THREAD

**Issue by derekc** [CTANZ/moodle-theme_decaf#14]
I know this was changed for a reason at some stage.
Is it possible for this to be an option?

-Derek

**Comment by pauln** [comment]
Hi Derek,
This is already an option:
![decaf-site-admin](https://cloud.githubusercontent.com/assets/574359/4926964/9eaa81b2-6537-11e4-9552-f9924937b5b8.png)

**Comment by derekc** [comment]
Ahh.  (sorry)
