### ISSUE TITLE
Unable to scroll horizontally when in "Grader report"

### ISSUE THREAD

**Issue by grantmucha** [CTANZ/moodle-theme_decaf#16]
Moodle - 2.8.2
Decaf - 2014010606  2.0 RC1

Works fine in "Clean" theme however does not work in latest version of "Decaf".

No attachments required, easy to verify.

**Comment by pauln** [comment]
Fixed in 2.0.5 (which has now been released in the Moodle.org plugins database).  Thanks for reporting this issue!
