### ISSUE TITLE
general.php causes parsing error in Moodle 2.2.3

### ISSUE THREAD

**Issue by HAZET** [CTANZ/moodle-theme_decaf#2]
I think it is line 93 where it should read <?php } ?>, not  <? } ?>

**Comment by pauln** [comment]
Thanks for reporting this.  <? } ?> works fine if you have PHP configured to allow "short tags" - but I'll change it so that you don't need short tags enabled.

**Comment by HAZET** [comment]
Oh. Yes sure, short tags. Still better to change it if those three missing characters are the only place short tags are used.
Thanks!
Henrik

Am 23.05.2012 um 22:41 schrieb "Paul Nicholls" reply@reply.github.com:

> Thanks for reporting this.  <? } ?> works fine if you have PHP configured to allow "short tags" - but I'll change it so that you don't need short tags enabled.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/leizhang/moodle-theme_decaf/issues/2#issuecomment-5884041

Henrik  Zawischa
Senior System Engineer

SONIC Performance Support GmbH

Cell:
E-Mail: Henrik.Zawischa@sonic-ps.de
Web: www.sonic-performance-support.co.nz

Facebook: www.facebook.com/SONICVideoTraining
YouTube: http://www.youtube.com/SONICVideoTraining
Twitter: www.twitter.com/VideoTraining
