### ISSUE TITLE
Unusual Label behaviour with VideoEasy plugin

### ISSUE THREAD

**Issue by derekc** [CTANZ/moodle-theme_decaf#21]
VideoEasy formatting does not work with Decaf.
With Decaf: http://vle.tpp.ac.nz/course/view.php?id=189
With Clean: http://vle.tpp.ac.nz/course/view.php?id=444

Forum formatting with decaf does work: http://vle.tpp.ac.nz/mod/forum/discuss.php?d=1947

-Derek

**Comment by derekc** [comment]
An update.
A friend has looked at the code.

"It appears that that using the Decaf theme causes the VideoEasy filter to return an empty result instead of the video player object.
It removes your video link from the page but does not replace it with anything at all.  The html source for the page does not contain any reference to the video, so it is not a javascript or CSS issue.
The issue remains after switching the theme until you clear the caches. This points towards the VideoEasy filter result being the problem, but something in Decaf is triggering this bug or conflicting with the VideoEasy filter.  I haven't looked at the PHP code yet"

So: works with Clean doesn't work with Decaf.  Puzzling.

-Derek

**Comment by pauln** [comment]
I looked at your sample links, and was able to determine that a small bit of CSS in Decaf causes the problem because it's applied too broadly.  It was initially added some time ago in order to fix a different issue, but I haven't been able to replicate the original issue in order to figure out whether the original fix is now redundant, or whether it needs rewriting to avoid this new conflict with the VideoEasy filter.

I'm currently on holiday, so won't be able to continue my research on this issue for a while.  In the mean time, you can try adding the following to "custom CSS" on the Decaf settings page (don't forget to clear the theme cache from the Theme Selector page, or purge all caches if you don't mind blowing away everything else too):
`ul.section li div {min-height:0;}`
That should override the troublesome rule and make the player appear correctly, though I can't guarantee that it won't cause other issues, since I haven't completed my testing.  I don't expect it to cause any issues, but please feel free to report back here with your results, either way.

**Comment by derekc** [comment]
I have three comments Paul:
1) thanks, I'll try this.
2) You are reading your emails on holiday?  I appreciate it, but you probably shouldn't.  :-)
3) Enjoy the break.

-Derek

**Comment by pauln** [comment]
Github emails go to my personal email account, because I use Github for non-work projects too - don't worry, I'm not reading work email ;-)

**Comment by derekc** [comment]
## I know I am probably having this little conversation with Paul all on my lonesome with me the only person in the known universe who wants Decaf + Videoeasy.  :-)  I will post this however: just in case I am wrong.  I'm going to try another tack later.  Paul, ignore this for now and enjoy your holiday.

The latest from my friend who has had a look at the Videoeasy clash with Decaf:

"I had 3 browsers showing a crossed-out style (it has been overridden) but it was still in effect!  That should not be possible.

Paul's fix doesn't fix it.  Set that min-height to 0 and the videos go to 0 height (instead of being tiny, they're not visible at all).

There's something in the Decaf page structure that messes up the CSS positioning even when I disabled the Decaf CSS.  Probably the awesome bar.  I couldn't figure out a perfect fix. The below SHOULD do the trick if you know the height of your videos:

.flowplayer {
  min-height: 180px !important;
  height: 100% !important;
}
.flowplayer div {min-height:0 !important}
.fp-playlist {height: 100% !important;}

BUT even though browsers SAY my height style is in effect on the 'fp-playlist' play button, the line from Decaf is actually still in effect:
ul.section li.label div {height: auto;}

So the 'play' button is almost invisible and is unusable.  I can't override it.  Decaf needs fixing or hacking.

These 2 Decaf lines are the worst, from core.css, line 106:
ul.section li div {min-height:23px;}
ul.section li.label div {height: auto;}

If those are removed, it _might_ fix things entirely but at worst, we could patch the height with CSS"

:-)  This looks like progress maybe.
-Derek

**Comment by JimThorpeNZ** [comment]
Hi Derek

Do you have a url that I can take a look at?

Jim Thorpe
Analyst Programmer - Application Support - Student
University of Canterbury, Dovedale Village, Room: DE04
Ext. 93149  :  Tel. +64 3 369 3149
jim.thorpe@canterbury.ac.nzmailto:jim.thorpe@canterbury.ac.nz

**Comment by derekc** [comment]
Jim:

Decaf + videoeasy: http://vle.tpp.ac.nz/course/view.php?id=189&section=1
Clean + Videoeasy: http://vle.tpp.ac.nz/course/view.php?id=444&section=3

Note: is you view with decaf, you often have to refresh a couple of times to get it to work when you then view it in clean.

I can give you a login if you want to delve deeper.

-Derek
(And thanks . . )

**Comment by derekc** [comment]
MONDAY 11TH MAY

## Some CSS below that has fixed the problems with VE+Decaf+FP AFAIK at this point.  From my friend working on this.  The issue remains: Clean does not fail.  There is a problem in needing to know the height with Decaf, but I THINK not Clean, but I'll need to clarify this.

/\* videoEasy Decaf patch.  Sadly needs to know video height */
.flowplayer {min-height: 180px !important;}
.flowplayer div {min-height:0 !important}
.flowplayer .fp-engine,
.flowplayer .fp-ui, 
.flowplayer .fp-message, 
.flowplayer .fp-buffer, 
.flowplayer .fp-waiting,
.flowplayer .fp-help,
.flowplayer .fp-volumelevel,
.flowplayer .fp-progress {
  height: 100% !important;
}

.flowplayer .fp-embed-code:before {height:0 !important}
.flowplayer.is-mouseout .fp-controls {height:0 !important}

.flowplayer.is-mouseout .fp-timeline
{height:4px !important}

.flowplayer .fp-volumeslider {height:5px !important}

.flowplayer .fp-timeline,
.flowplayer.is-touch.is-mouseover .fp-progress:before,
.flowplayer .fp-progress:after {height:10px !important;}

.flowplayer .fp-volume,
.flowplayer .fp-mute {height:15px !important}

.flowplayer .fp-controls,
.flowplayer .fp-embed,
.flowplayer .fp-play
{height:20px !important}

.flowplayer .fp-close {height:23px !important}

.flowplayer .fp-play {height:24px !important}

**Comment by pauln** [comment]
This should be fixed in 2.0.7 (which will be released in the Moodle plugins database shortly).
