### ISSUE TITLE
Testing with Moodle 3.0

### ISSUE THREAD

**Issue by derekc** [CTANZ/moodle-theme_decaf#25]
Yes I know I am jumping the gun!!
Beta, instal Decaf, set course them to defac.

One tiny error with full debug on.

Notice: Undefined index: alt in /home/dev.tpp.ac.nz/public_html/lib/outputrenderers.php on line 1291

That is all.  :-)

-Derek

**Comment by pauln** [comment]
Hi Derek,
Please update to Decaf 2.1.0 - it includes a fix for this issue.
