### ISSUE TITLE
Change password error when using decaf theme

### ISSUE THREAD

**Issue by jsofronis** [CTANZ/moodle-theme_decaf#26]
Hello ,
I am using Decaf theme with Moodle 3.0 version. When we create new user in Moodle and tick force password change option during setting and user is logged in Moodle it shows below error :

Error detectat. cal que l'arregli un programador: session_is_loggedinas() is removed, use \core\session\manager::is_loggedinas() instead

Vés al contingut principal
Error detectat. cal que l'arregli un programador: session_is_loggedinas() is removed, use \core\session\manager::is_loggedinas() instead
Debug info:
Error code: codingerror
Stack trace:
line 422 of /lib/deprecatedlib.php: coding_exception thrown
line 18 of /theme/decaf/layout/navbar.inc.php: call to session_is_loggedinas()
line 44 of /theme/decaf/layout/columns2.php: call to include()
line 1016 of /lib/outputrenderers.php: call to include()
line 946 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 155 of /login/change_password.php: call to core_renderer->header()

**Comment by ruckelzug** [comment]
Replace "session_is_loggedinas()" with " \core\session\manager::is_loggedinas()" in line 18 of /theme/decaf/layout/navbar.inc.php.
Now the users can change there password.
(Testet with Moodle 3.1)

**Comment by derekc** [comment]
It is possible this thread may help
https://moodle.org/mod/forum/discuss.php?d=328965

-Derek

**Comment by jsofronis** [comment]
Thanks for your responses
