### ISSUE TITLE
Any upgrade?

### ISSUE THREAD

**Issue by jsofronis** [CTANZ/moodle-theme_decaf#30]
Is there any thought of upgrading decaf version for moodle 3.3.x and even 3.4.x ?

**Comment by grantmucha** [comment]
Upgrading it how, does it not already work?

**Comment by jsofronis** [comment]
I havent tried this yet because of the fear that it may hangs during the upgare to the last moodle version (3.4.x)

**Comment by grantmucha** [comment]
I am running Decaf for a few clients without issue on 3.3.3+ (20171201) but had to make a few small changes. I can't see it changing much to 3.4 but won't actually try until they release 3.4.1 (rule of thumb) when upgrading. If you need help shoot me an email sales@dedicatedhosting.me.

**Comment by pauln** [comment]
I no longer work with Moodle on a daily basis, so I unfortunately don't have much time for plugin maintenance these days.  If you've got fixes for Moodle 3.3 compatibility, please submit a pull request @UltraFlux - I'll try to find time to review it (and other pending PRs) in the near future.

**Comment by pauln** [comment]
I've just released Decaf v2.2.0, which supports Moodle 3.1 to 3.4.

@jsofronis, I haven't explicitly tested upgrading to Moodle 3.4 from an earlier version; I'm not aware of any Decaf-related reason why such an upgrade would hang, though.  If you're concerned about the possibility of issues during the upgrade, I'd suggest doing a trial run on a test site (which could be a complete copy of your live site, if it's not too big to clone reasonably) - and always make sure that you have a full backup (and the ability to restore it) before you try upgrading it.
