### ISSUE TITLE
New Message Centre in 3.6.1

### ISSUE THREAD

**Issue by Tigger996** [CTANZ/moodle-theme_decaf#31]
I hope this theme is still being worked on.  I upgraded to Moodle 3.6.1 and decaf does not work with the new message centre.  It appeared to be working fine but apparently it's not and I cannot revert back.

Any chance this can be fixed?

Thanks

**Comment by pauln** [comment]
I've just released [Decaf v2.3.0](https://moodle.org/plugins/pluginversion.php?id=18688), which should fix this (by adding support for the new Messaging UI).  If you encounter any further issues with the v2.3.0 release, please report them here on Github.

**Comment by Tigger996** [comment]
Thanks for the quick fix!
