### ISSUE TITLE
deprecated error on Moodle 2.6

### ISSUE THREAD

**Issue by PeloNZ** [CTANZ/moodle-theme_decaf#7]
Hi, I've just begun testing the decaf theme on a 2.6 site. There is deprecated code error  coming up.

get_system_context() is deprecated, please use context_system::instance() instead.
line 4080 of /lib/deprecatedlib.php: call to debugging()
line 756 of /theme/decaf/lib.php: call to get_system_context()
line 1652 of /lib/navigationlib.php: call to decaf_expand_navigation->add_category()
line 2400 of /lib/navigationlib.php: call to global_navigation->load_all_categories()
line 805 of /theme/decaf/lib.php: call to global_navigation->add_course()
line 1478 of /lib/navigationlib.php: call to decaf_expand_navigation->add_course()
line 823 of /theme/decaf/lib.php: call to global_navigation->load_all_courses()
line 817 of /theme/decaf/lib.php: call to decaf_expand_navigation->load_all_courses()
line 519 of /theme/decaf/lib.php: call to decaf_expand_navigation->load_courses_other()
line 503 of /theme/decaf/lib.php: call to decaf_expand_navigation->expand()
line 459 of /theme/decaf/lib.php: call to decaf_expand_navigation->initialise()
line 338 of /theme/decaf/renderers.php: call to decaf_expand_navigation->__construct()
line 273 of /theme/decaf/renderers.php: call to theme_decaf_topsettings_renderer->navigation_node()
line 22 of /theme/decaf/layout/general.php: call to theme_decaf_topsettings_renderer->navigation_tree()
line 866 of /lib/outputrenderers.php: call to include()
line 796 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 107 of /admin/settings.php: call to core_renderer->header()

**Comment by pauln** [comment]
Fixed in 455d8e2bb85358cc565bf302144e8df68b79eb35.  Decaf 1.9RC2 will be uploaded to the moodle.org plugins repository shortly.
