### ISSUE TITLE
Decaf 2 on moodle 2.7 columns

### ISSUE THREAD

**Issue by danbuntu** [CTANZ/moodle-theme_decaf#8]
Hi

I'm in the process of upgrading a moodle 2.3 that use decaf to moodle 2.7.

On the old site when the left hand column is empty it hides so that you have a wider middle column and then a right hand hand.

On the new decaf 2 it seems that when the left hand column is empty it still displays - it's permanently set to be a 3 column page.

is this correct? Is the this now going to be the way the theme works or will the old left hand column hiding be be reinstated?

**Comment by pauln** [comment]
This should now be fixed in RC1; the Settings and Navigation blocks were causing this if hidden using the Decaf settings rather than by removing them from the page.
