### ISSUE TITLE
Editing topic field placement 

### ISSUE THREAD

**Issue by aaranmcguire** [CTANZ/moodle-theme_decaf#9]
Hey,

I'm not sure if this is just on our instance, as I would of thought it would be fixed by now.

But when we go into a course and go to edit a topic title we see this.

![image 1](http://f.cl.ly/items/1b0m0z1M1u3X0A3f2f06/Image%202014-08-30%20at%208.37.54%20PM.png)

After removing `.mform .fitem fieldset.felement{float:left;}`

it goes back to normal,

![image 2](http://f.cl.ly/items/2W450o3P3R3h2Z053G0d/Image%202014-08-30%20at%208.38.03%20PM.png)

Is anyone else having this issue? or is it just us?

**Comment by pauln** [comment]
Hi,
Which version of Moodle are you running, and which version of Decaf are you seeing this issue in?  I can't replicate it in Decaf 1.9 on Moodle 2.4, or in Decaf 2.0 on Moodle 2.6 or 2.7

-Paul

**Comment by aaranmcguire** [comment]
For Decaf I'm on 1.9.0 RC5 (2013112504) and for Moodle, I'm on 2.7.1 (20140807)..

I got decaf from git clone, I just looked and I assume master is not version 2.0 of Decaf

**Comment by aaranmcguire** [comment]
Just updated to version 2.0 RC1 and the issue is fixed, but its a big style change for our staff just to fix one issue. Would you be able to check you instance on my config and let me know if its affecting you.

**Comment by pauln** [comment]
I've been able to confirm it.  I've had a brief look around and can't see any negative side-effects, so I've merged your pull request.  I'll do a version bump and new release soon.
